# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snapshots' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapshots

  target 'SnapshotsTests' do
      use_frameworks!
      pod 'iOSSnapshotTestCase'
      pod 'SnapshotTesting', '~> 1.9.0'
  end

  target 'SnapshotsUITests' do
      use_frameworks!
      pod 'iOSSnapshotTestCase'
  end

end
